import type { BriefingAnalysis } from '@/types/hybrid'
import BriefingCard from '@/components/briefings/BriefingCard'

export default function BriefingList({ briefings }: { briefings: BriefingAnalysis[] }) {
  if (briefings.length === 0) {
    return (
      <div className="surface-panel p-10 text-center">
        <p className="text-base font-medium text-foreground">No briefings yet.</p>
        <p className="mt-2 text-sm text-muted-foreground">
          The morning summary generated by the hybrid engine will appear here.
        </p>
      </div>
    )
  }

  return (
    <div className="space-y-4">
      {briefings.map((briefing) => (
        <BriefingCard key={briefing.id} briefing={briefing} />
      ))}
    </div>
  )
}
